<?php
namespace app\admin\controller;
use library\Response;
use app\common\model\LiveItem as LiveItemModel;
use app\common\model\Live as LiveModel;
use app\common\model\LiveItemDetail;
use app\common\model\LiveItemDraw;
use app\common\model\LiveItemView;
use app\common\model\LiveItemAnswer;
use app\common\model\Coupon as CouponModel;
use app\common\model\GiftActivity;
class LiveActivity extends Base{

    protected $award_type = array(
        1 => '优惠券',
        2 => '红包',
        3 => '充换码',
    );

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $item_id = (int)$this->request->param('item_id');
        $live_id = (int)$this->request->param('live_id');
        $liveModel = new LiveModel();
        $info = $liveModel->getDetail(array('id'=>$live_id));
        $this->assign('info',$info);
        $this->assign('item_id',$item_id);
        $this->assign('live_id',$live_id);
    }

    //问答列表
    public function list_answer(){
        if($this->request->isPost()){
            $this->request->filter(['strip_tags', 'htmlspecialchars']);
            $item_id = (int)$this->request->param('item_id');
            $live_id = (int)$this->request->param('live_id');
            $page      = (int)$this->request->post('page', 0);
            $limit      = (int)$this->request->post('limit', 0);
            $offset = empty($page)?0:($page-1)*$limit;

            $liveItemAnswerModel = new LiveItemAnswer();
            $couponModel = new CouponModel();
            $giftActivityModel = new GiftActivity();
            $condition = array();
            $condition['item_id'] = $item_id;
            $condition['live_id'] = $live_id;
            $count = $liveItemAnswerModel->fetchCount($condition);
            $list  = array();
            if ( 0 < $count ) {
                $list = $liveItemAnswerModel->fetchList($condition,$offset,$limit);
                foreach ($list as &$value){
                    switch ($value['reward_type']){
                        case 1://优惠券
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 2://红包
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 3://充换码
                            $value['ext_id'] = $giftActivityModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                    }
                    $value['reward_type'] = $this->award_type[$value['reward_type']];
                }
            }
            Response::Json(0,"请求成功",$count,$list);
        }
        return $this->view->fetch();
    }

    //添加问答
    public function answer(){
        $data['item_id'] = $this->request->param('item_id');
        $data['live_id'] = $this->request->param('live_id');
        if($this->request->isAjax()){
            $data['time'] = (int)$this->request->param('time');
            $data['question'] = $this->request->param('question');
            $data['answer_1'] = $this->request->param('answer_1');
            $data['answer_2'] = $this->request->param('answer_2');
            $data['answer_3'] = $this->request->param('answer_3');
            $data['correct_answer'] = (int)$this->request->param('correct_answer');
            $data['status'] = (int)$this->request->param('status');
            $data['reward_type'] = (int)$this->request->param('coupon_type');
            $data['ext_id'] = (int)$this->request->param('ext_id');
            $liveItemAnswerModel = new LiveItemAnswer();
            $id = $liveItemAnswerModel->insertGetId($data);
            if($id<=0){
                $this->error('添加失败');
            }
            $this->success('添加成功');
        }

        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$data['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$data['item_id']);
        $this->assign('live_id',$data['live_id']);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }

    //编辑问答
    public function edit_answer(){
        $id = (int)$this->request->param('id');
        $liveItemAnswerModel = new LiveItemAnswer();
        $liveItemDetail = $liveItemAnswerModel ->getDetail(array('id'=>$id));
        if($this->request->isAjax()){
            $data['status'] = (int)$this->request->param('status');
            $update = $liveItemAnswerModel->update($data,array('id'=>$id));
            if(false === $update){
                $this->error('更新失败');
            }
            $this->success('更新成功');
        }
        $couponModel = new CouponModel();
        $giftActivityModel = new GiftActivity();
        switch ($liveItemDetail['reward_type']){
            case 1://优惠券
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 2://红包
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 3://充换码
                $reward_name = $giftActivityModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
        }
        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$liveItemDetail['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$liveItemDetail['item_id']);
        $this->assign('live_id',$liveItemDetail['live_id']);
        $this->assign('liveItemDetail',$liveItemDetail);
        $this->assign('reward_type',$this->award_type[$liveItemDetail['reward_type']]);
        $this->assign('reward_name',$reward_name);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }


    //抽奖列表
    public function list_draw(){
        if($this->request->isPost()){
            $this->request->filter(['strip_tags', 'htmlspecialchars']);
            $item_id = (int)$this->request->param('item_id');
            $live_id = (int)$this->request->param('live_id');
            $page      = (int)$this->request->post('page', 0);
            $limit      = (int)$this->request->post('limit', 0);
            $offset = empty($page)?0:($page-1)*$limit;

            $liveItemDrawModel = new LiveItemDraw();
            $couponModel = new CouponModel();
            $giftActivityModel = new GiftActivity();
            $condition = array();
            $condition['item_id'] = $item_id;
            $condition['live_id'] = $live_id;
            $count = $liveItemDrawModel->fetchCount($condition);
            $list  = array();
            if ( 0 < $count ) {
                $list = $liveItemDrawModel->fetchList($condition,$offset,$limit);
                foreach ($list as &$value){
                    switch ($value['reward_type']){
                        case 1://优惠券
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 2://红包
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 3://充换码
                            $value['ext_id'] = $giftActivityModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                    }
                    $value['reward_type'] = $this->award_type[$value['reward_type']];
                }
            }
            Response::Json(0,"请求成功",$count,$list);
        }
        return $this->view->fetch();
    }

    //添加抽奖
    public function draw(){
        $data['item_id'] = $this->request->param('item_id');
        $data['live_id'] = $this->request->param('live_id');
        if($this->request->isAjax()){
            $data['time'] = (int)$this->request->param('time');
            $data['num'] = (int)$this->request->param('num');
            $data['status'] = (int)$this->request->param('status');
            $data['reward_type'] = (int)$this->request->param('coupon_type');
            $data['ext_id'] = (int)$this->request->param('ext_id');
            $liveItemDrawModel = new LiveItemDraw();
            $id = $liveItemDrawModel->insertGetId($data);
            if($id<=0){
                $this->error('添加失败');
            }
            $this->success('添加成功');
        }

        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$data['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$data['item_id']);
        $this->assign('live_id',$data['live_id']);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }

    //编辑抽奖
    public function edit_draw(){
        $id = (int)$this->request->param('id');
        $liveItemDrawModel = new LiveItemDraw();
        $liveItemDetail = $liveItemDrawModel ->getDetail(array('id'=>$id));
        if($this->request->isAjax()){
            $data['status'] = (int)$this->request->param('status');
            $data['num'] = (int)$this->request->param('num');
            $update = $liveItemDrawModel->update($data,array('id'=>$id));
            if(false === $update){
                $this->error('更新失败');
            }
            $this->success('更新成功');
        }
        $couponModel = new CouponModel();
        $giftActivityModel = new GiftActivity();
        switch ($liveItemDetail['reward_type']){
            case 1://优惠券
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 2://红包
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 3://充换码
                $reward_name = $giftActivityModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
        }
        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$liveItemDetail['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$liveItemDetail['item_id']);
        $this->assign('live_id',$liveItemDetail['live_id']);
        $this->assign('liveItemDetail',$liveItemDetail);
        $this->assign('reward_type',$this->award_type[$liveItemDetail['reward_type']]);
        $this->assign('reward_name',$reward_name);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }


    //观看赠礼列表
    public function list_view(){
        if($this->request->isPost()){
            $this->request->filter(['strip_tags', 'htmlspecialchars']);
            $item_id = (int)$this->request->param('item_id');
            $live_id = (int)$this->request->param('live_id');
            $page      = (int)$this->request->post('page', 0);
            $limit      = (int)$this->request->post('limit', 0);
            $offset = empty($page)?0:($page-1)*$limit;

            $liveItemViewModel = new LiveItemView();
            $couponModel = new CouponModel();
            $giftActivityModel = new GiftActivity();
            $condition = array();
            $condition['item_id'] = $item_id;
            $condition['live_id'] = $live_id;
            $count = $liveItemViewModel->fetchCount($condition);
            $list  = array();
            if ( 0 < $count ) {
                $list = $liveItemViewModel->fetchList($condition,$offset,$limit);
                foreach ($list as &$value){
                    switch ($value['reward_type']){
                        case 1://优惠券
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 2://红包
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 3://充换码
                            $value['ext_id'] = $giftActivityModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                    }
                    $value['reward_type'] = $this->award_type[$value['reward_type']];
                }
            }
            Response::Json(0,"请求成功",$count,$list);
        }
        return $this->view->fetch();
    }

    //添加观看赠礼
    public function view(){
        $data['item_id'] = $this->request->param('item_id');
        $data['live_id'] = $this->request->param('live_id');
        if($this->request->isAjax()){
            $data['time'] = (int)$this->request->param('time');
            $data['status'] = (int)$this->request->param('status');
            $data['reward_type'] =(int)$this->request->param('coupon_type');
            $data['ext_id'] = (int)$this->request->param('ext_id');
            $liveItemViewModel = new LiveItemView();
            $id = $liveItemViewModel->insertGetId($data);
            if($id<=0){
                $this->error('添加失败');
            }
            $this->success('添加成功');
        }

        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$data['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$data['item_id']);
        $this->assign('live_id',$data['live_id']);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }

    //编辑观看赠礼
    public function edit_view(){
        $id = (int)$this->request->param('id');
        $liveItemViewModel = new LiveItemView();
        $liveItemDetail = $liveItemViewModel ->getDetail(array('id'=>$id));
        if($this->request->isAjax()){
            $data['status'] = (int)$this->request->param('status');
            $update = $liveItemViewModel->update($data,array('id'=>$id));
            if(false === $update){
                $this->error('更新失败');
            }
            $this->success('更新成功');
        }
        $couponModel = new CouponModel();
        $giftActivityModel = new GiftActivity();
        switch ($liveItemDetail['reward_type']){
            case 1://优惠券
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 2://红包
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 3://充换码
                $reward_name = $giftActivityModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
        }
        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$liveItemDetail['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$liveItemDetail['item_id']);
        $this->assign('live_id',$liveItemDetail['live_id']);
        $this->assign('liveItemDetail',$liveItemDetail);
        $this->assign('reward_type',$this->award_type[$liveItemDetail['reward_type']]);
        $this->assign('reward_name',$reward_name);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }

    //单次互动列表
    public function list_single(){
        if($this->request->isPost()){
            $this->request->filter(['strip_tags', 'htmlspecialchars']);
            $item_id = (int)$this->request->param('item_id');
            $live_id = (int)$this->request->param('live_id');
            $page      = (int)$this->request->post('page', 0);
            $limit      = (int)$this->request->post('limit', 0);
            $offset = empty($page)?0:($page-1)*$limit;

            $liveItemDetailModel = new LiveItemDetail();
            $couponModel = new CouponModel();
            $giftActivityModel = new GiftActivity();
            $condition = array();
            $condition['item_id'] = $item_id;
            $condition['live_id'] = $live_id;
            $count = $liveItemDetailModel->fetchCount($condition);
            $list  = array();
            if ( 0 < $count ) {
                $list = $liveItemDetailModel->fetchList($condition,$offset,$limit);
                foreach ($list as &$value){
                    switch ($value['reward_type']){
                        case 1://优惠券
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 2://红包
                            $value['ext_id'] = $couponModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                        case 3://充换码
                            $value['ext_id'] = $giftActivityModel->where(array('id'=>$value['ext_id']))->column('title')[0];
                            break;
                    }
                    $value['interact_type'] = LiveItemModel::$interact_type[$value['type']];
                    $value['reward_type'] = $this->award_type[$value['reward_type']];
                }
            }
            Response::Json(0,"请求成功",$count,$list);
        }
        return $this->view->fetch();
    }

    //添加单次互动
    public function single(){
        $data['item_id'] = $this->request->param('item_id');
        $data['live_id'] = $this->request->param('live_id');
        if($this->request->isAjax()){
            $data['type'] = (int)$this->request->param('interact_type');
            $data['status'] = (int)$this->request->param('status');
            $data['reward_type'] = (int)$this->request->param('coupon_type');
            $data['ext_id'] = (int)$this->request->param('ext_id');
            $liveItemDetailModel = new LiveItemDetail();
            $id = $liveItemDetailModel->insertGetId($data);
            if($id<=0){
                $this->error('添加失败');
            }
            $this->success('添加成功');
        }

        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$data['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$data['item_id']);
        $this->assign('live_id',$data['live_id']);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }

    //编辑单次互动
    public function edit_single(){
        $id = (int)$this->request->param('id');
        $liveItemDetailModel = new LiveItemDetail();
        $liveItemDetail = $liveItemDetailModel ->getDetail(array('id'=>$id));
        if($this->request->isAjax()){
            $data['status'] = (int)$this->request->param('status');
            $update = $liveItemDetailModel->update($data,array('id'=>$id));
            if(false === $update){
                $this->error('更新失败');
            }
            $this->success('更新成功');
        }
        $couponModel = new CouponModel();
        $giftActivityModel = new GiftActivity();
        switch ($liveItemDetail['reward_type']){
            case 1://优惠券
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 2://红包
                $reward_name = $couponModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
            case 3://充换码
                $reward_name = $giftActivityModel->where(array('id'=>$liveItemDetail['ext_id']))->column('title')[0];
                break;
        }
        $LiveItemModel = new LiveItemModel();
        $item = $LiveItemModel->getDetail(array('item_id'=>$liveItemDetail['item_id']));
        $this->assign('title',$item['item_name']);
        $this->assign('item_id',$liveItemDetail['item_id']);
        $this->assign('live_id',$liveItemDetail['live_id']);
        $this->assign('liveItemDetail',$liveItemDetail);
        $this->assign('reward_type',$this->award_type[$liveItemDetail['reward_type']]);
        $this->assign('reward_name',$reward_name);
        $this->assign('interact_type',LiveItemModel::$interact_type);
        return $this->view->fetch();
    }
}