<?php
// +----------------------------------------------------------------------
// | 直播管理
// +----------------------------------------------------------------------
// | Author: Wuyh 2020-02-06
// +----------------------------------------------------------------------
namespace app\admin\controller;

use think\Db;
use app\common\model\Live AS LiveModel;
use app\common\model\LiveGoods;
use think\Exception;
use Endroid\QrCode\QrCode;

class Live extends Base
{
    //模型
    protected $model;

    const API_URL = 'https://open.weixin.qq.com/sns/getexpappinfo';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new LiveModel();
    }

    /**
     * 列表
     * @return string
     * @throws \think\Exception
     */
    public function index()
    {
        if ($this->request->isAjax()) return $this->model->tableData(input('param.'));

        return $this->view->fetch();
    }

    /**
     * 编辑
     * @return string
     * @throws \think\Exception
     */
    public function edit()
    {
        $result = ['code' => 0, 'msg' => '获取失败', 'data' => []];
        $id = request()->param('id', 0);
        if (!$id) return $this->error('无此直播');
        $info = $this->model->find(['id' => $id]);

        if (empty($info)) return json($result);
        $adminList = model('common/AdminUser')->getAll();

        if ($this->request->isGet()) return $this->view->fetch('', ['info' => $info, 'adminList' => $adminList]);
        if ($this->request->isPost()) {
            $params = input('post.');
            $ret = $this->model->toAdd($params);
            if ($ret['code'] == 1) return json(['code' => 1, 'msg' => '修改成功']);
            return json(['code' => 0, 'msg' => $ret['msg']]);
        };
    }

    /**
     * 创建
     * @return string|\think\response\Json
     * @throws \think\Exception
     */
    public function add()
    {
        $adminList = model('common/AdminUser')->getAll();
        if ($this->request->isGet()) return $this->view->fetch('edit', ['info' => json_encode([]), 'adminList' => $adminList]);
        if ($this->request->isPost()) {
            $params = input('post.');
            $ret = $this->model->toAdd($params);

            if ($ret['code'] == 1) return json(['code' => 1, 'msg' => '添加成功']);
            return json(['code' => 0, 'msg' => $ret['msg']]);
        };
    }

    /**
     * 删除
     * @param $id
     * @return \think\response\Json
     */
    public function del($id)
    {
        Db::startTrans();
        try {
           if(false === LiveModel::destroy($id)) throw new Exception('失败');
           if(false === LiveGoods::destroy(['live_id' => $id])) throw new Exception('失败');
           Db::commit();
           return json(['code' => 1, 'data' => '', 'msg' => '成功']);
        }
        catch (Exception $e) {
            Db::rollback();
            return json(['code' => 0, 'data' => '', 'msg' => $e->getMessage()]);
        }
    }

    /**
     * 查看直播二维码
     * @param $id
     * @return string
     * @throws Exception
     */
    public function viewQrcode($id)
    {
        return $this->view->fetch('',['id' => $id]);
        //https://open.weixin.qq.com/sns/getexpappinfo?appid=wxd6a0ed842b361563&path=pages%2findex%2findex.html%3flive_id%3d20#wechat-redirect
    }

    /**
     * 生成主播二维码
     * @param $id
     */
    public function qrcode($id)
    {
        //https://open.weixin.qq.com/sns/getexpappinfo?appid=wxd6a0ed842b361563&path=pages/home/home.html?live_id=20#wechat-redirect
        $url = self::API_URL .'?appid='. config('cfg')['WX_MINI_APP_ID'] .'&path=';
        $qrc_data = $url.urlencode('pages/index/index.html?live_id='.$id)."#wechat-redirect";

        $qrCode = new QrCode($qrc_data);
        header('Content-Type: '.$qrCode->getContentType());
        echo $qrCode->writeString();
    }
}