<?php
// +----------------------------------------------------------------------
// | 订单管理
// +----------------------------------------------------------------------
// | modify: Wuyh 2020-03-05
// +----------------------------------------------------------------------
namespace app\admin\controller;
use app\common\model\PayOrder;

class Order extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new PayOrder();
    }

    /**
     * 列表
     * @return string
     * @throws \think\Exception
     * @author
     */
    public function index()
    {
        if ($this->request->isAjax()) return $this->model->tableData(input('param.'));
        return $this->view->fetch();
    }

    /**
     * 查看详情
     * @param $id
     * @return string
     * @throws \think\Exception
     */
    public function view($id)
    {
        if (empty($id)) $this->error('参数错误');
        $info = $this->model->with(['GoodsOrder'])->find(['id' => $id]);

        if (empty($info)) $this->error('没有找到订单信息');
        $info['paytype_name'] = config('enum.order_pay')['type'][$info['paytype']];

        return $this->view->fetch('', ['info' => $info]);
    }
}