<?php
// +----------------------------------------------------------------------
// | 队列管理
// +----------------------------------------------------------------------
// | Copyright (c) 2019-2020 rights reserved.
// +----------------------------------------------------------------------
// | Author: wuyh
// +----------------------------------------------------------------------
// | Date: 2020/3/28 15:26
// +----------------------------------------------------------------------

namespace app\admin\controller;

use app\common\model\SwooleQueue;

class Queue extends Base
{
    protected $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new SwooleQueue();
    }

    /**
     * 列表
     * @return string
     */
    public function index()
    {
        if ($this->request->isAjax()) return $this->model->tableData(input('param.'));
        return $this->view->fetch();
    }

    /**
     * 新增
     * @return array|string
     * @Author: wuyh
     * @Date: 2020/3/28 16:16
     */
    public function add()
    {
        if ($this->request->isGet()) return $this->view->fetch('edit', ['info' => []]);
        if ($this->request->isPost()) {
            $params = input('post.');
            $ret = $this->model->toAdd($params);
            if ($ret['code'] == 1) return (['code' => 1, 'msg' => '添加成功']);
            return json_return( 0,  '添加失败');
        };
    }

    public function edit()
    {
        $id = request()->param('id', 0);
        if (!$id) return $this->error('没有找相应信息');
        $info = $this->model->find(['id' => $id]);
        if (empty($info)) return json_return(0, '获取失败');

        if ($this->request->isGet()) return $this->view->fetch('', ['info' => $info]);
        if ($this->request->isPost()) {
            $params = input('post.');
            $ret = $this->model->toAdd($params);
            if ($ret['code'] == 1) return json_return(1, '修改成功');
            return json_return(0,$ret['msg']);
        };

    }
}