<?php
// +----------------------------------------------------------------------
// | 配置组
//
//管理
// +----------------------------------------------------------------------
// | Author: Wuyh 2020-02-13
// +----------------------------------------------------------------------
namespace app\admin\controller;

use think\Db;
use app\common\model\SysConfigGroup AS SysConfigGroupModel;
use think\Exception;

class SysConfigGroup extends Base
{
    //配置表模型
    protected $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->model = new SysConfigGroupModel();
    }

    /**
     * 列表
     * @return string
     * @throws \think\Exception
     */
    public function index()
    {
        if ($this->request->isAjax()) return $this->model->tableData(input('param.'));
        return $this->view->fetch();
    }

    /**
     * 数形格式列表
     * @return \think\response\Json
     */
    public function getTree()
    {
        $params = input('post.');
        $result = ['code' => 1, 'msg' => '', 'data' => []];
        if ($this->request->isAjax()) $result['data'] = $this->model->getTree($params);
        return json($result);
    }


    /**
     * 编辑
     * @return string
     * @throws \think\Exception
     */
    public function edit()
    {
        $id = request()->param('id', 0);
        if (!$id) $this->error('ID参数错误');

        $info = $this->model->find(['id' => $id]);
        if (empty($info)) $this->error('没有找到相应信息');
        if ($this->request->isGet()) return $this->view->fetch('', ['info' => $info]);
        if ($this->request->isPost()) return $this->model->toAdd(input('post.'));
    }

    /**
     * 创建
     * @return string|\think\response\Json
     * @throws \think\Exception
     */
    public function add()
    {
        $groupId = request()->param('pid', 0);
        if ($this->request->isGet()) return $this->view->fetch('edit', ['info' => ['pid' => $groupId]]);
        if ($this->request->isPost()) return $this->model->toAdd(input('post.'));
    }

    /**
     * 删除
     * @param $id
     * @return \think\response\Json
     */
    public function del($id)
    {
        Db::startTrans();
        try {
           if(false === SysConfigGroupModel::destroy($id)) throw new Exception('失败');
           if(false === SysConfigGroupModel::destroy(['pid' => $id])) throw new Exception('失败');
           Db::commit();
           return json(['code' => 1, 'data' => '', 'msg' => '成功']);
        }
        catch (Exception $e) {
            Db::rollback();
            return json(['code' => 0, 'data' => '', 'msg' => $e->getMessage()]);
        }
    }
}