<?php
// +----------------------------------------------------------------------
// | 直播间互动基类
// +----------------------------------------------------------------------
// | Copyright (c) 2019-2020 rights reserved.
// +----------------------------------------------------------------------
// | Author: wuyh
// +----------------------------------------------------------------------
// | Date: 2020/3/21 14:04
// +----------------------------------------------------------------------
namespace app\swoole\controller;
use think\Controller;
use think\Cache;
use think\Config;

class Base extends Controller
{
    /**
     * Redis
     * @var
     */
    protected $redis;


    public function _initialize()
    {
        $this->redis = Cache::connect(Config::get('cache.redis'));
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 是否登录
     * @Author: wuyh
     * @Date: 2020/3/19 15:34
     */
    public function checkLogin($data)
    {
        if (!isset($data['token']) || empty($data['token'])) return json_encode(['code' => 0, 'msg' => '缺少token']);
        $token = $data['token'];

        $ret = ture;

        if (!$ret) return json_encode(['code' => 0, 'msg' => '未登录']);
    }

}