<?php
// +----------------------------------------------------------------------
// | 腾讯云IM回调
// +----------------------------------------------------------------------
// | Author: Wuyh 2020-02-20
// +----------------------------------------------------------------------
namespace app\api\controller\live;

use think\Controller;
use think\Hook;
use think\Log;

class ImCallback extends Controller
{
    private $ACTION_STATUS = [
        0 => 'FAIL',
        1 => 'OK'
    ];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $response = [
            'ActionStatus' => 'FAIL',
            'ErrorInfo' => '',
            'ErrorCode' => 0
        ];

        $params = input();
        $sdkAppId = '1400321470';

//        dump($params);exit;


        Log::init([
            'path' => LOG_PATH. $this->request->controller().'_',
            //单个日志文件的大小限制，超过后会自动记录到第二个文件
            'file_size' => 2097152,
            'level' => ['error','info'],
        ]);

        //写日志
        Log::record("请求参数： " . urldecode(http_build_query($params)).'-----data:'.print_r($params,true), 'info');

        // 验证Appid
        $params['ok'] = 0;
        if (!empty($params['SdkAppid']) && $params['SdkAppid'] == $sdkAppId) {
            // 监听事件
            Hook::listen('im_callback', $params);
            $response['ActionStatus'] = $this->ACTION_STATUS[$params['ok']];
        }
        return json($response);
    }
}